# Compose file for AMD GPU

# If not working, try DirectML instead:
# https://github.com/YanWenKun/ComfyUI-Docker/blob/main/docs/wsl-directml.adoc

services:

  file-chown:
    container_name: file-chown
    build:
      context: .
      dockerfile: Dockerfile-rocm
    image: "yanwk/comfyui-boot:rocm"
    user: "root"
    volumes: 
      - "./storage:/home/runner"
    command: "chown -R runner:runner /home/runner"

# Ref: https://hub.docker.com/r/rocm/pytorch
# Ref: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html
# docker run --device=/dev/kfd --device=/dev/dri \
#   --group-add=video --ipc=host --cap-add=SYS_PTRACE \
#   --security-opt seccomp=unconfined

  comfyui:
    init: true
    container_name: comfyui
    depends_on:
      file-chown:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile-rocm
    image: "yanwk/comfyui-boot:rocm"
    ports:
      - "8188:8188"
    volumes:
      - "./storage:/home/runner"
    environment:
      - CLI_ARGS=--use-pytorch-cross-attention
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
